#!/usr/bin/env bash

# Set up autograder files

AG=$AGROOT/autograder/

# update assignment repository
pushd $AG/source/assignment
git pull
popd

export PYTHONPATH=$AG/source/assignment/checkerutils:$PYTHONPATH

# run assignment-specific checker
$AG/source/assignment/run_checker




